### 32

Используя модуль array и библиотеку numpy, решить следующие задачи:
- а) Дан массив  𝐴  размера  𝑁 . Сформировать новый массив B того же размера по следующему правилу: элемент BK равен сумме элементов массива  𝐴  с номерами от  𝐾  до  𝑁 .
- б) Дана матрица размера  𝑀×𝑁 . Упорядочить ее строки так, чтобы их первые элементы образовывали возрастающую последовательность.

In [1]:
from array import array
import numpy as np

а)

In [2]:
N = int(input('Введите количество элементов в массиве: '))

arrA = array('i', [])
for _ in range(N):
    a = int(input('Введите элемент массива: '))
    arrA.append(a)
print(arrA)

Введите количество элементов в массиве: 5
Введите элемент массива: 1
Введите элемент массива: 2
Введите элемент массива: 3
Введите элемент массива: 4
Введите элемент массива: 5
array('i', [1, 2, 3, 4, 5])


In [3]:
arrB = array('i', [])
for i in range(N):
    summaK_N = 0
    for k in range(i, N):
        summaK_N += arrA[k]
    arrB.append(summaK_N)
print(arrB)

array('i', [15, 14, 12, 9, 5])


In [4]:
# альтернативный вариант
A = np.array([1, 2, 3, 4, 5])
B = np.zeros_like(A)

for k in range(len(A)):
    B[k] = np.sum(A[k:])

print(B)

[15 14 12  9  5]


б)

In [5]:
M = int(input('Введите количество строк в матрице: '))
N = int(input('Введите количество столбцов в матрице: '))

arrM_N = []
for i in range(M):
    row = []
    for j in range(N):
        e = int(input('Введите элемент матрицы ({}, {}): '.format(i+1, j+1)))
        row.append(e)
    arrM_N.append(row)
arrM_N = np.array(arrM_N)
print(arrM_N)

Введите количество строк в матрице: 3
Введите количество столбцов в матрице: 3
Введите элемент матрицы (1, 1): 7
Введите элемент матрицы (1, 2): 8
Введите элемент матрицы (1, 3): 9
Введите элемент матрицы (2, 1): 1
Введите элемент матрицы (2, 2): 2
Введите элемент матрицы (2, 3): 3
Введите элемент матрицы (3, 1): 4
Введите элемент матрицы (3, 2): 5
Введите элемент матрицы (3, 3): 6
[[7 8 9]
 [1 2 3]
 [4 5 6]]


In [6]:
sorted_arrM_N = arrM_N[arrM_N[:,0].argsort()]
print(sorted_arrM_N)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 33

Дан стек. Необходимо проверить, является ли его содержимое последовательностью арифметической прогрессии.

In [1]:
from collections import deque

class Stack(deque):
    def push(self, a):
        self.append(a)

In [2]:
N = int(input('Введите количество элементов в стеке: '))
S = Stack()
for _ in range(N):
    el = int(input('Введите элемент для добавления в стек: '))
    S.push(el)
print(S)

Введите количество элементов в стеке: 5
Введите элемент для добавления в стек: 1
Введите элемент для добавления в стек: 2
Введите элемент для добавления в стек: 3
Введите элемент для добавления в стек: 4
Введите элемент для добавления в стек: 5
Stack([1, 2, 3, 4, 5])


In [3]:
def checking_for_arithmetic_progression(stack, N):
    for i in range(N-2):
        if stack[i+1]-stack[i] != stack[i+2]-stack[i+1]:
            return False
    return True

In [4]:
checking_for_arithmetic_progression(S, N)

True

### 34

Создать класс очереди, который будет хранить только элементы определенного типа данных. Тип элементов задается при инициализации объекта класса очереди. При добавлении элемента, если его тип не соответствует заданному, то он не должен добавляться.

In [5]:
from typing import Type, List

class Queue(deque):
    def __init__(self, element_type: Type):
        super().__init__()
        self.element_type = element_type
        self.elements: List[element_type] = [] # объявление атрибута elements в классе MyClass 
                                               # как списка элементов определенного типа
    def enqueue(self, a):
        if not isinstance(a, self.element_type):
            print(f"Неверный тип элемента. Ожидался тип {self.element_type}.")
            return None
        self.append(a)

    def dequeue(self):
        return self.popleft()

In [6]:
Q = Queue(int)
Q.enqueue('element')

Неверный тип элемента. Ожидался тип <class 'int'>.


In [7]:
Q.enqueue(1)
Q.enqueue(2)
Q.enqueue(3)
print(Q)

Queue([1, 2, 3])


### 35

Создайте двусвязный список для хранения информации о заказах в интернетмагазине. Каждый элемент списка должен содержать номер заказа, дату создания, список товаров, их количество и стоимость, а также информацию о доставке и оплате.

In [50]:
class Order:
    def __init__(self, order_number, creation_date, products, delivery_info, payment_info):
        self.order_number = order_number
        self.creation_date = creation_date
        self.products = products
        self.delivery_info = delivery_info
        self.payment_info = payment_info
        self.prev = None # ссылка на предыдущий заказ
        self.next = None # ссылка на следующий заказ

# Пример создания элементов двусвязного списка
order1 = Order(1, "14.05.2024", ["Товар1", "Товар2"], [2, 3], 150.50)
order2 = Order(2, "14.04.2024", ["Товар3", "Товар4"], [1, 2], 80.25)
order3 = Order(3, "14.03.2024", ["Товар5"], [1], 30.00)
orders = [order1, order2, order3]

# Связывание элементов в двусвязный список
for i in range(len(orders)-1):
    orders[i].next = orders[i+1]
for i in range(1, len(orders)):
    orders[i].prev = orders[i-1]

# Пример обращения к элементам списка
current_order = orders[0]
while current_order:
    print(f"Номер заказа: {current_order.order_number}")
    print(f"Дата создания: {current_order.creation_date}")
    print(f"Список товаров: {current_order.products}")
    print(f"Количество товаров: {current_order.products}")
    print(f"Стоимость заказа: {current_order.payment_info}")
    print(f"Информация о доставке: {current_order.delivery_info}")
    print(f"Информация об оплате: {current_order.payment_info}")
    print("-------------------------")
    current_order = current_order.next

Номер заказа: 1
Дата создания: 14.05.2024
Список товаров: ['Товар1', 'Товар2']
Количество товаров: ['Товар1', 'Товар2']
Стоимость заказа: 150.5
Информация о доставке: [2, 3]
Информация об оплате: 150.5
-------------------------
Номер заказа: 2
Дата создания: 14.04.2024
Список товаров: ['Товар3', 'Товар4']
Количество товаров: ['Товар3', 'Товар4']
Стоимость заказа: 80.25
Информация о доставке: [1, 2]
Информация об оплате: 80.25
-------------------------
Номер заказа: 3
Дата создания: 14.03.2024
Список товаров: ['Товар5']
Количество товаров: ['Товар5']
Стоимость заказа: 30.0
Информация о доставке: [1]
Информация об оплате: 30.0
-------------------------


### 36

Реализовать функцию, которая разделяет двусвязный список на два списка, один из которых содержит все элементы, меньшие заданного значения, а другой — все элементы, большие или равные заданному значению.

In [20]:
class Node(): # класс для создания узла с информацией data
    def __init__(self, data):
        self.data = data
        self.prev = None
        self.next = None

class DoublyLinkedList: # класс для создания двусвязного списка
    def __init__(self):
        self.head = None
        self.tail = None
        
    def add_node(self, data): # добавление узла в конец двунаправленного списка 
        new_node = Node(data)
        if not self.head:
            self.head = new_node
            self.tail = new_node
        else:
            new_node.prev = self.tail
            self.tail.next = new_node
            self.tail = new_node
            
    def add_node_alternative(self, data): # альтернативный вариант добавления узла 
        new_node = Node(data)
        if self.head is None:
            self.head = new_node
        else:
            current = self.head
            while current is not None:
                current = current.next
            current.next = new_node
            new_node.prev = current
            
    def __str__(self): # магический метод для вывода информации
        if self.head == None:
            return 'Двусвязный список пуст'
        current = self.head
        dllist_str = ''
        while current:
            dllist_str += ' <> ' + str(current.data)
            current = current.next
        return dllist_str.lstrip(' <> ')
    
# .lstrip() используется для удаления пробельных символов с начала строки,
# метод будет удалять указанные символы только с начала строки

In [51]:
DLL = DoublyLinkedList()
DLL.add_node(1)
DLL.add_node(2)
DLL.add_node(3)
DLL.add_node(4)
print(DLL)

1 <> 2 <> 3 <> 4


In [52]:
dll1 = DoublyLinkedList()
dll2 = DoublyLinkedList()

def distribution(head, value):
    current = head
    while current:
        if current.data < value:
            dll1.add_node(current.data)
        elif current.data >= value:
            dll2.add_node(current.data)
        current = current.next
        
distribution(DLL.head, 3)
print(dll1)
print(dll2)

1 <> 2
3 <> 4


### 37

Реализовать функцию, которая проверяет, содержится ли заданный элемент в циклическом двусвязном списке.

In [38]:
class DoublyLinkedList_cyclical: # класс для создания двусвязного списка
    def __init__(self):
        self.head = None
        self.tail = None
        
    def add_node(self, data):
        new_node = Node(data)
        if self.head is None:
            self.head = new_node
            self.tail = new_node
            new_node.next = self.head
            new_node.prev = self.head
        else:
            new_node.prev = self.tail
            new_node.next = self.head
            self.tail.next = new_node
            self.tail = new_node
            self.head.prev = self.tail
            
    def display_list(self):
        current = self.head
        while current is not None and current.next is not self.head:
            print(current.data)
            current = current.next
        if current is not None:
            print(current.data)
          

In [40]:
DLL_cycl = DoublyLinkedList_cyclical()
DLL_cycl.add_node(1)
DLL_cycl.add_node(2)
DLL_cycl.add_node(3)
DLL_cycl.add_node(4)
DLL_cycl.display_list()

1
2
3
4


In [49]:
def distribution(head, value):
    current = head
    while current is not None and current.next is not head:
        if current.data == value:
            return True
        current = current.next
    if current is not None:
        if current.data == value:
            return True
    return False
        
distribution(DLL_cycl.head, 10), distribution(DLL_cycl.head, 3)

(False, True)